name: SLSA3 Build

description: >-
  A named Action that you have at in your source repo .github/actions/slsa-build/action.yml.
  The Workflow `attest-build-provenance-sls3-rw` will search invoke this action to run
  your build. You man have any steps or invoke yet another Action.

runs:
  using: composite
  steps:
    - name: build
      shell: bash
      run: |
        date > gundam
        date > myhero
        ls -lah
