# Building and attesting are performed in two separated Jobs to elevate to SLSA3.
# This workflow requires a `./slsa_build.sh` at the repository root to run your build.

# This workflow invokes your Build Action at `.github/actions/slsa-build`'s `action.yml`
# Example `.github/actions/slsa-build/action.yml`

# name: SLSA3 Build
# description: >-
#   A named Action that you have at in your source repo .github/actions/slsa-build/action.yml.
#   The Workflow `attest-build-provenance-sls3-rw` will search invoke this action to run
#   your build. You man have any steps or invoke yet another Action.
# runs:
#   using: composite
#   steps:
#     - name: build
#       shell: bash
#       run: make release

# Example workflow invocation:

# jobs:
#   build-and-attest:
#     permissions:
#       id-token: write
#       attestations: write
#       contents: read
#     uses: ramonpetgrave/github-build-attestations-rw/.github/workflows/attest-build-provenance-slsa3-rw.yml@dev
#     with:
#       build-runner-label: ubuntu-latest
#       subject-path: |
#         ./gundam
#         ./myhero

name: Attest Build Provenance SLSA3 Resuable Workflow

permissions: {}

on:
  workflow_call:
    inputs:
      build-artifact-name:
        description: >
          The name of Github workflow artifact to store the subject files
        default: slsa3_build_artifact
        required: false
        type: string
      build-attestation-name:
        description: >
          The name of Github workflow artifact to store the attestation bundle file
        default: slsa3_build_attestation
        required: false
        type: string
      subject-path:
        description: >
          Path to the artifact serving as the subject of the attestation. May contain a
          glob pattern or list of paths (total subject count cannot exceed 2500).
          See https://github.com/actions/upload-artifact?tab=readme-ov-file#examples.
        required: true
        type: string
      show-summary:
        description: >
          Whether to attach a list of generated attestations to the workflow run
          summary page. Defaults to true.
        default: true
        required: false
        type: boolean
      build-github-token:
        description: >
          The GitHub token used as environment variable GH_TOKEN to ./slsa_build.sh.
        default: ${{ github.token }}
        required: false
        type: string
      build-runner-label:
        description: >
          The runner label to pass to `runs-on:`. e.g., "ubuntu-latest". 
        required: true
        type: string

jobs:
  run-slsa-build-action:
    outputs:
      job-id: ${{ github.job }}
      artifact-id: ${{ steps.upload-artifact.outputs.artifact-id }}
    permissions:
      contents: read
    runs-on: ${{ inputs.build-runner-label }}
    steps:
      - name: detect-runner
        if: ${{ runner.environment != 'github-hosted' }}
        run: echo "self-hosted runner detected, failing job!" && exit 1
      - name: checkout-source-repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7
      - name: slsa-build
        if: ${{ runner.environment == 'github-hosted' }}
        uses: ./.github/actions/slsa-build
        env:
          GITHUB_TOKEN: ${{ inputs.build-github-token }}
      - name: upload-artifact
        id: upload-artifact
        uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a #v4.3.6
        with:
          name: ${{ inputs.build-artifact-name }}
          path: ${{ inputs.subject-path }}
          if-no-files-found: error

  attest-build-artifacts:
    needs: run-slsa-build-action
    permissions:
      id-token: write
      attestations: write
    runs-on: ubuntu-latest
    steps:
      - name: debug-context
        run: |
          echo github.job ${{ github.job }}
          echo github.workflow ${{ github.workflow }}
      - name: detect-runner
        if: ${{ runner.environment != 'github-hosted' }}
        run: echo "self-hosted runner detected, failing job!" && exit 1
      - name: detect-build-job-runner
        # Get the job id number of `run-slsa-build-action`. Then get the logs of the "Set up job" activity.
        # these logs contain markers that identity use of self-hosted runners.
        # "Machine name:" should only appear in the logs for self-hosted runners.
        # See
        # - https://github.com/actions/runner/pull/539/files#diff-e10dd2daf26c47f8e2914b189bbbc8043bdcd073c633c9a2d29d67f0ec3b4581R77
        # - https://github.com/orgs/community/discussions/111347#discussioncomment-10490619
        # Since there may be multiple Jobs named `run-slsa-build-action`, and our Job name is particular, we retrieve the logs for all 
        # Jobs with that name.
        env:
          REPO: ${{ github.repository }}
          RUN_ID: ${{ github.run_id }}
          RUN_ATTEMPT: ${{ github.run_attempt }}
          GH_TOKEN: ${{ github.token }}
        run: |
          BUILD_JOB_IDS=$(
            gh run view "$RUN_ID" --repo "$REPO" --attempt "$RUN_ATTEMPT" --json jobs \
                --jq '.jobs[] | select((.conclusion="success") and (.name | endswith("run-slsa-build-action"))) | .databaseId'
          )
          while read -r ID; do
              echo getting "Set up job" logs for Job "$ID"
              JOB_LOGS=$( gh run view "$RUN_ID" --repo "$REPO" --job "$ID" --log | sed -n -e '/Set up job/I,/Complete job name/I p' )
              ABORT=false
              if grep -qi "Machine name:" <<< "$JOB_LOGS"; then
                  echo "detected a self-hosted runner, aborting attestation!"
                  ABORT=true
              else
                  echo "self-hosted runner not detected."
              fi
          done <<< "$BUILD_JOB_IDS"
          if [ "$ABORT" = true ]; then
              echo "Detected self hosted runner. Aborting"
              exit 1
          else
              echo "No self hosted runner detected. Proceeding."
              exit 0
          fi
      # actions/download-artifact@v4 does not yet support downloading via the immutable artifact-id,
      # but the Javascript library does. See: https://github.com/actions/download-artifact/issues/349
      - run: npm install @actions/artifact@2.1.9
      - name: download-artifact
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        env:
          ARTIFACT_ID: ${{ needs.run-slsa-build-action.outputs.artifact-id }}
        with:
          script: |
            const {default: artifactClient} = require('@actions/artifact')
            const { ARTIFACT_ID } = process.env
            await artifactClient.downloadArtifact(ARTIFACT_ID)
      - run: ls -lahR
      - name: attest-build-provenance
        if: ${{ runner.environment == 'github-hosted' }}
        id: attest-build-provenance
        uses: actions/attest-build-provenance@310b0a4a3b0b78ef57ecda988ee04b132db73ef8 # v1.4.1
        with:
          subject-path: ./*
          show-summary: ${{ inputs.show-summary }}
      - name: upload-provenance
        uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a #v4.3.6
        with:
          name: ${{ inputs.build-attestation-name }}
          path: ${{ steps.attest-build-provenance.outputs.bundle-path }}
          if-no-files-found: error

  verify:
    needs: attest-build-artifacts
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
      LOCAL_ATTESTATION_FILEPATH: ./attestation.jsonl
      ARTIFACTS_FOLDER: ./artifacts
      # OWNER: ramonpetgrave
      SOURCE_REPO: ramonpetgrave/github-build-attestations-rw
      SOURCE_REF: ${{ github.ref }}
      # SIGNER_REPO: ramonpetgrave/ramonpetgrave
      SIGNER_WORKFLOW: >-
        ramonpetgrave/github-build-attestations-rw/.github/workflows/attest-build-provenance-slsa3-rw.yml
      SIGNER_WORKFLOW_AND_REF: >-
        ramonpetgrave/github-build-attestations-rw/.github/workflows/attest-build-provenance-slsa3-rw.yml@refs/heads/dev
      SIGNER_WORKFLOW_CERT_IDENTITY: >-
        https://github.com/ramonpetgrave/github-build-attestations-rw/.github/workflows/attest-build-provenance-slsa3-rw.yml@refs/heads/dev
      # CERT_IDENTITY_REGEX: >-
        # ^https://github.com/ramonpetgrave/github-build-attestations-rw/.github/workflows/attest-build-provenance-slsa3-rw.yml@v[0-9].[0-9].[0-9]$
    steps:
      - name: detect-runner
        if: ${{ runner.environment != 'github-hosted' }}
        run: echo "self-hosted runner detected, failing job!" && exit 1
      - name: download-artifact
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 #v4.1.8
        with:
          name: ${{ inputs.build-artifact-name }}
          path: ${{ env.ARTIFACTS_FOLDER }}
      - name: ls
        run: ls -lahR
      - name: online-verify-with-cert-identity
        run: |
          for FILE in "$ARTIFACTS_FOLDER"/*; do
            gh attestation verify \
              $FILE \
              --deny-self-hosted-runners \
              --repo "$SOURCE_REPO" \
              --cert-identity "$SIGNER_WORKFLOW_CERT_IDENTITY" \
              --format json --jq '.[].verificationResult.signature.certificate.sourceRepositoryRef' \
            | grep "^$SOURCE_REF$"
          done