# This workflow requires a `./slsa_build.sh` at the repository root to run your build.
# Building and attesting are performed in two separated Jobs to elevate to SLSA3.
# Example:

# jobs:
#   build-and-attest:
#     permissions:
#       id-token: write
#       attestations: write
#       contents: read
#     uses: ramonpetgrave/github-build-attestations-rw/.github/workflows/attest-build-provenance-slsa3-rw.yml@dev
#     with:
#       subject-path: |
#         ./gundam
#         ./myhero

name: Attest Build Provenance SLSA3 Resuable Workflow

permissions: {}

on:
  workflow_call:
    inputs:
      build-artifact-name:
        description: >
          The name of Github workflow artifact to store the subject files
        default: slsa3_build_artifact
        required: false
        type: string
      build-attestation-name:
        description: >
          The name of Github workflow artifact to store the attestation bundle file
        default: slsa3_build_attestation
        required: false
        type: string
      subject-path:
        description: >
          Path to the artifact serving as the subject of the attestation. May contain a
          glob pattern or list of paths (total subject count cannot exceed 2500).
          See https://github.com/actions/upload-artifact?tab=readme-ov-file#examples.
        required: true
        type: string
      show-summary:
        description: >
          Whether to attach a list of generated attestations to the workflow run
          summary page. Defaults to true.
        default: true
        required: false
        type: boolean
      github-token:
        description: >
          The GitHub token used as environment variable GH_TOKEN to ./slsa_build.sh.
        default: ${{ github.token }}
        required: false
        type: string

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: checkout-source-repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7
      - name: build
        run: ./slsa_build.sh
        env:
          GITHUB_TOKEN: ${{ inputs.subject-path }}
      - name: upload-artifact
        uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a #v4.3.6
        with:
          name: ${{ inputs.build-artifact-name }}
          path: ${{ inputs.subject-path }}
          if-no-files-found: error

  attest:
    needs: build
    permissions:
      id-token: write
      attestations: write
    runs-on: ubuntu-latest
    steps:
      - name: download-artifact
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 #v4.1.8
        with:
          name: ${{ inputs.build-artifact-name }}
      - name: attest-build-provenance
        id: attest-build-provenance
        uses: actions/attest-build-provenance@310b0a4a3b0b78ef57ecda988ee04b132db73ef8 # v1.4.1
        with:
          subject-path: ${{ inputs.subject-path }}
          show-summary: ${{ inputs.show-summary }}
      - name: upload-provenance
        uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a #v4.3.6
        with:
          name: ${{ inputs.build-attestation-name }}
          path: ${{ steps.attest-build-provenance.outputs.bundle-path }}
          if-no-files-found: error

  verify:
    needs: attest
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
      # OWNER: ramonpetgrave
      REPO: ramonpetgrave/github-build-attestations-rw
      SIGNER_REPO: ramonpetgrave/ramonpetgrave
      SIGNER_WORKFLOW: >-
        ramonpetgrave/github-build-attestations-rw/.github/workflows/attest-build-provenance-slsa3-rw.yml
      SIGNER_WORKFLOW_AND_REF: >-
        ramonpetgrave/github-build-attestations-rw/.github/workflows/attest-build-provenance-slsa3-rw.yml@refs/heads/dev
      CERT_IDENTITY: >-
        https://github.com/ramonpetgrave/github-build-attestations-rw/.github/workflows/attest-build-provenance-slsa3-rw.yml@refs/heads/dev
      CERT_IDENTITY_REGEX: >-
        ^https://github.com/ramonpetgrave/github-build-attestations-rw/.github/workflows/attest-build-provenance-slsa3-rw.yml@v[0-9].[0-9].[0-9]$
    steps:
      - name: download-artifact
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 #v4.1.8
        with:
          name: ${{ inputs.build-artifact-name }}
      - name: with-signer-workflow
        run: |
          for FILE in ./*; do
            gh attestation verify \
              $FILE \
              --repo "$REPO" \
              --signer-workflow "$SIGNER_WORKFLOW"
          done
      - name: with-signer-workflow-and-ref
        run: |
          for FILE in ./*; do
            gh attestation verify \
              $FILE \
              --repo "$REPO" \
              --signer-workflow "$SIGNER_WORKFLOW_AND_REF"
          done
      - name: with-signer-workflow-and-wrong-ref
        run: |
          for FILE in ./*; do
            gh attestation verify \
              $FILE \
              --repo "$REPO" \
              --signer-workflow "$SIGNER_WORKFLOW_AND_REF".rc-1
          done
      - name: with-cert-identity
        run: |
          for FILE in ./*; do
            gh attestation verify \
              $FILE \
              --repo "$REPO" \
              --cert-identity "$CERT_IDENTITY"
          done
      - name: with-semever-cert-identity-regex
        run: |
          for FILE in ./*; do
            gh attestation verify \
              $FILE \
              --repo "$REPO" \
              --cert-identity-regex "$CERT_IDENTITY_REGEX"
          done
