name: debug slsa3 build

on: 
  push:
  workflow_dispatch:

jobs:
  build-and-attest:
    permissions:
      id-token: write
      attestations: write
      contents: read
    uses: ramonpetgrave/github-build-attestations-rw/.github/workflows/attest-build-provenance-slsa3-rw.yml@dev
    with:
      subject-path: |
        ./gundam
        ./myhero
